-- Drop tables if they already exist
DROP TABLE IF EXISTS purchase_order_tbl;
DROP TABLE IF EXISTS products_tbl;

CREATE TABLE products_tbl (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE purchase_order_tbl (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products_tbl(product_id)
);

