spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/orders
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/orders
    user: postgres
    password: password
  cloud:
    function:
      definition: fluxSupplier;fluxConsumer
    stream:
      bindings:
        fluxSupplier-out-0:
          destination: order-created
        fluxConsumer-in-0:
          destination: order-updated
server:
  port: 8003
logging:
  level:
    org:
      springframework:
        r2dbc:
          core: DEBUG